#!/usr/bin/env ruby
# frozen_string_literal: true

require 'tls-checker'

require 'riemann/client'

require 'optparse'

options = {
  riemann: {
    host: '127.0.0.1',
    port: 5555,
  },
}

OptionParser.new do |opts|
  opts.banner = 'Usage: riemann-tls-checker [options] hostname...'

  opts.on('-h', '--host=HOST', 'Connect to riemann on host HOST') do |v|
    options[:riemann][:host] = v
  end
  opts.on('-p', '--port=PORT', 'Connect to riemann on port PORT') do |v|
    options[:riemann][:port] = v
  end
end.parse!

factory = CertificateCheckerFactory.new

r = Riemann::Client.new(options[:riemann])

ARGV.each do |arg|
  factory.certificate_checkers_for(arg).each do |checker|
    r.tcp << checker.to_e
  end
end
