#!/usr/bin/env ruby
# frozen_string_literal: true

require 'tls-checker'

factory = CertificateCheckerFactory.new

ARGV.each do |arg|
  factory.certificate_checkers_for(arg).each do |checker|
    puts checker.to_e
  end
end
